### ISSUE TITLE
Return machine group ID in /api/timetable

### ISSUE THREAD

**Issue by MachHach** [Raphx/vmlauncher-server#18]
As shown in the [Swagger API doc](https://app.swaggerhub.com/api/Raphx/vmlauncher-server/1.0.0), the endpoint _/api/timetable_ only returns `name` as the only attribute of a Machine Group object.

The `id` should also be returned as it is needed by Machines to match corresponding Machine Group parent via ID comparison.

**Comment by Raphx** [comment]
Hi, fixed this. The endpoint should now indicates the inclusion `id` field for Machine Group object.

It is actually already indicated in the swagger api doc, and I just realized that the `allOf` field is not used correctly, which erroneously (?) works previously. 😖 

Fixes is also made on the following endpoints,

  - */api/machine-groups*
  - */api/machines*
  - */api/machines/{id}/installation*

Closing this issue on fix.
