### ISSUE TITLE
Functionality: Switch to allow/disallow installation on Machine

### ISSUE THREAD

**Issue by MachHach** [Raphx/vmlauncher-server#19]
Suggested implementation:
Add a Boolean variable to Machine object.
This Boolean variable acts as the ticket on whether to allow users to install build with the launcher client.
As usual, the way to modify this variable is by using a HTTP POST request to the Machine object.

The use case for this is that during a scheduled test run, the test scheduler can use this functionality to lock/unlock target Machine objects so that users are prevented from interfering with the test run.

**Comment by Raphx** [comment]
Project maintenance ended.
